apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  labels:
    app: template-workspace-material
  name: template-workspace-material
  namespace: tpl-d
spec:
  clusterIP: 172.22.234.149
  clusterIPs:
  - 172.22.234.149
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: 8443-tcp
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app: template-workspace-material
    deployment: template-workspace-material
  sessionAffinity: None
  type: ClusterIP
