######################################################################################################################################
##
## Values file to configure projects
##
## Documentation references:
## LimitRanges: https://docs.openshift.com/container-platform/4.12/nodes/clusters/nodes-cluster-limit-ranges.html
## Resource quota: https://docs.openshift.com/container-platform/4.12/applications/quotas/quotas-setting-per-project.html
## Network policy: https://docs.openshift.com/container-platform/4.12/networking/network_policy/about-network-policy.html
## Grant users access to project: https://computingforgeeks.com/grant-user-access-to-project-in-openshift/
##
######################################################################################################################################
defaultSettings:
  resources:
    enabled: true
    quota:
      hard:
        pods: "5"
        requests.cpu: "2"
        requests.memory: "3Gi"
        limits.cpu: "4"
        limits.memory: "5Gi"
        requests.storage: "50Gi"
  roleSettings:
    enabled: true
    roleBindings:
      - role: "admin"
        identities:
          - name: "ocpadmins"
            type: "Group"
          - name: "ocpadmin"
            type: "User"
      - role: "edit"
        identities:
          - name: "developer"
            type: "User"
  networkSettings:
    enabled: true
    networkPolicies:
      ingress:
        fromNamespaces:
          - namespace: kube-apiserver-operator
            labels:
              - labelName: "kubernetes.io/metadata.name"
                labelValue: "openshift-kube-apiserver-operator"
            podSelectors:
              - labelName: "app"
                labelValue: "kube-apiserver-operator"
        fromPods:
          - podName: test-app
            labels:
              - labelName: "app"
                labelValue: "test"
            podSelectors:
              - labelName: "app"
                labelValue: "kube-apiserver-operator"
      egress:
        toNamespaces:
          - namespace: kube-apiserver-operator
            labels:
              - name: "kubernetes.io/metadata.name"
                value: "openshift-kube-apiserver-operator"
            podSelectors:
              - labelName: "app"
                labelValue: "kube-apiserver-operator"
        toPods:
          - podName: test-app
            labels:
              - labelName: "app"
                labelValue: "test"
            podSelectors:
              - labelName: "app"
                labelValue: "kube-apiserver-operator"
        toCidrs:
          - cidrName: "ldap"
            cidr:
              - 192.168.57.1/32
            ports:
              - protocol: TCP
                port: 636
              - protocol: TCP
                port: 389
            podSelectors:
              - labelName: "app"
                labelValue: "kube-apiserver-operator"

projects:
  my-test-project:
    metaData:
      displayName: "My test project"
      description: |
        This is just a test
        project to test the template
      requester: hhue
    resources:
      enabled: true

  xx-project:
    metaData:
      displayName: "XX project"
      requester: hhue
    roleSettings:
      enabled: true
      roleBindings:
        - role: "admin"
          identities:
            - name: "ocpadmins"
              type: "Group"
            - name: "ocpadmin"
              type: "User"
        - role: "edit"
          identities:
            - name: "developer"
              type: "User"
    resources:
      enabled: true
      quota:
        hard:
          pods: "3"
          requests.cpu: "1"
          requests.memory: "7Gi"
          limits.cpu: "3"
          limits.memory: "10Gi"
          persistentvolumeclaims: "7"
          requests.storage: "70Gi"
