{{- $appName := "dummy" }}

{{- range .Values.deployments }}
{{- $appName = .name }}
{{- range .routes }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: {{ $appName }}
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
spec:
  host: {{ .hostname }}
  path: {{ .path }}
  port:
    targetPort: {{ .port }}-{{ .protocol | lower }}
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: {{ .servicename }}
    weight: 100
  wildcardPolicy: None
{{- end }}
{{- end }}
