apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: "2023-10-20T11:44:47Z"
  labels:
    app: template-workspace-material
  name: template-workspace-material
  namespace: tpl-d
  resourceVersion: "109250649"
  uid: 02a3fb49-a9ac-4679-9788-99d791de3ed3
spec:
  clusterIP: 172.22.205.63
  clusterIPs:
  - 172.22.205.63
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: 8443-tcp
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app: template-workspace-material
    deployment: template-workspace-material
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
