{{- $thisChart := .Chart }}
{{- $thisRelease := .Release }}
{{- $thisValues := .Values }}
{{- range $projectName, $currentProject := .Values.projects }}
---
apiVersion: project.openshift.io/v1
kind: Project
metadata:
  labels:
{{- include "create-labels" (list $thisChart $thisRelease $thisValues ) | indent 4 }}
  annotations:
    openshift.io/description: "{{ $currentProject.metaData.description }}"
    openshift.io/display-name: "{{ $currentProject.metaData.displayName | default "" }}"
    openshift.io/requester: "{{ $currentProject.metaData.requester }}"
  name: "{{ $projectName }}"
spec: {}

{{- include "create-rolebindings" (list $ $projectName $currentProject ) }}
{{- include "create-resource-quota" (list $ $projectName $currentProject ) }}
{{- include "create-network-policy" (list $ $projectName $currentProject ) }}
{{- end }}
