{{- $thisChart := .Chart }}
{{- $thisRelease := .Release }}
{{- $thisValues := .Values }}
{{- range $projectName, $currentProject := .Values.projects }}
{{- $requestor :=  required "For every project \"metaData.requester\" is required ..." $currentProject.metaData.requester }}
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
{{- include "create-namespace-annotations" (list $currentProject ) | indent 4 }}
  labels:
{{- include "create-labels" (list $thisChart $thisRelease $thisValues ) | indent 4 }}
  name: "{{ $projectName }}"
spec:
  finalizers:
  - kubernetes
---
{{- include "create-rolebindings" (list $ $projectName $currentProject ) }}
{{- include "create-resource-quota" (list $ $projectName $currentProject ) }}
{{- include "create-network-policy" (list $ $projectName $currentProject ) }}
{{- include "create-limit-ranges" (list $ $projectName $currentProject ) }}
{{- end }}
