apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: jenkins-agent
      app.kubernetes.io/component: jenkins-agent
      app.kubernetes.io/instance: jenkins-agent
    name: jenkins-agent
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: registry.redhat.io/ocp-tools-4/jenkins-agent-base-rhel8:v4.12.0-1686649619
      from:
        kind: DockerImage
        name: registry.redhat.io/ocp-tools-4/jenkins-agent-base-rhel8:v4.12.0-1686649619
      generation: null
      importPolicy: {}
      name: v4.12.0-1686649619
      referencePolicy:
        type: ""
  status:
    dockerImageRepository: ""
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"jenkins-agent:v4.12.0-1686649619"},"fieldPath":"spec.template.spec.containers[?(@.name==\"jenkins-agent\")].image"}]'
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: jenkins-agent
      app.kubernetes.io/component: jenkins-agent
      app.kubernetes.io/instance: jenkins-agent
    name: jenkins-agent
  spec:
    replicas: 1
    selector:
      matchLabels:
        deployment: jenkins-agent
    strategy: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          deployment: jenkins-agent
      spec:
        containers:
        - image: ' '
          name: jenkins-agent
          resources: {}
  status: {}
kind: List
metadata: {}
