{{- range .Values.routes }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: {{ .name }}
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
spec:
  host: {{ $.Values.hostname }}
  path: {{ .path }}
  port:
    targetPort: {{ .port.number }}-{{ .port.protocol | lower }}
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: {{ .servicename }}
    weight: 100
  wildcardPolicy: None
{{- end }}
