apiVersion: v1
kind: Service
metadata:
  labels:
    app: template-workspace-material
  name: template-workspace-material
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: 8443-tcp
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app: template-workspace-material
    deployment: template-workspace-material
  sessionAffinity: None
  type: ClusterIP
